services:
  minecraft-server:
    container_name: minecraft-server
    build: .
    ports:
      - "0.0.0.0:38246:38246"
    volumes:
      - ./server:/server
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4GB
        reservations:
          cpus: '4'
          memory: 1GB
    command: [ "tail", "-f", "/dev/null" ]
