services:
  minecraft-server:
    build: .
    ports:
      - "0.0.0.0:25565:25565"
    volumes:
      - ./server/server.properties:/server/server.properties
      - ./server/mods:/server/mods
      - ./server/world:/server/world
    environment:
      - EULA=true
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]
