services:
  minecraft-server:
    container_name: minecraft-server
    build: .
    ports:
      - "0.0.0.0:25565:25565"
    volumes:
      - ./server/server.properties:/server/server.properties
      - ./server/mods:/server/mods
      - ./server/world/BrunoAndCecilia:/server/BrunoAndCecilia
    environment:
      - EULA=true
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4GB
        reservations:
          cpus: '2'
          memory: 2GB
